name: 'Omni-Dev Commit Check'
description: 'Validate commit messages against project guidelines using AI-powered analysis'
author: 'rust-works'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  # API Keys - at least one required
  anthropic-api-key:
    description: 'Anthropic API key for Claude models'
    required: false
  openai-api-key:
    description: 'OpenAI API key (set use-openai: true to use)'
    required: false

  # Provider selection
  use-openai:
    description: 'Use OpenAI instead of Anthropic'
    required: false
    default: 'false'
  use-ollama:
    description: 'Use Ollama for local inference'
    required: false
    default: 'false'

  # Model configuration
  model:
    description: 'AI model to use (e.g., claude-sonnet-4-5-20250929, gpt-4.1)'
    required: false
    default: 'claude-sonnet-4-5-20250929'

  # Ollama-specific
  ollama-base-url:
    description: 'Ollama server URL (default: http://localhost:11434)'
    required: false
  ollama-model:
    description: 'Ollama model name'
    required: false

  # AWS Bedrock configuration
  use-bedrock:
    description: 'Use AWS Bedrock for Claude'
    required: false
    default: 'false'
  bedrock-base-url:
    description: 'AWS Bedrock endpoint URL'
    required: false
  bedrock-auth-token:
    description: 'AWS Bedrock auth token'
    required: false
  skip-bedrock-auth:
    description: 'Skip Bedrock authentication (for proxied endpoints)'
    required: false
    default: 'false'

  # Commit range configuration
  commit-range:
    description: 'Commit range to check (e.g., HEAD~5..HEAD). Defaults to commits ahead of base branch'
    required: false
  base-branch:
    description: 'Base branch to compare against (defaults to main/master)'
    required: false

  # Guidelines configuration
  guidelines:
    description: 'Path to custom commit guidelines file'
    required: false
  context-dir:
    description: 'Custom context directory for loading guidelines'
    required: false
    default: '.omni-dev/'

  # Output configuration
  format:
    description: 'Output format: text, json, or yaml'
    required: false
    default: 'text'

  # Behavior configuration
  strict:
    description: 'Exit with error code if any warnings found'
    required: false
    default: 'false'
  quiet:
    description: 'Only show errors/warnings, suppress info-level output'
    required: false
    default: 'false'
  verbose:
    description: 'Show detailed analysis including model info'
    required: false
    default: 'false'
  show-passing:
    description: 'Include passing commits in output'
    required: false
    default: 'false'
  no-suggestions:
    description: 'Skip generating corrected message suggestions'
    required: false
    default: 'false'

  # Performance configuration
  batch-size:
    description: 'Number of commits to process per AI request'
    required: false
    default: '4'

  # Debug configuration
  debug:
    description: 'Enable debug logging (sets RUST_LOG=debug)'
    required: false
    default: 'false'

  # Version configuration
  version:
    description: 'omni-dev version to use (e.g., 0.13.0, latest)'
    required: false
    default: 'latest'

  # Main branch behavior
  skip-on-main:
    description: 'Skip commit check when running on main/master branch (cache will still be populated)'
    required: false
    default: 'true'

  # Cache configuration
  cache-prefix:
    description: 'Prefix to prepend to the cache key for the omni-dev binary'
    required: false
    default: ''

  # Installation method
  use-prebuilt-binary:
    description: 'Download pre-built binary from GitHub releases instead of building from source via cargo install'
    required: false
    default: 'true'

outputs:
  result:
    description: 'Check result in the specified format'
  exit-code:
    description: 'Exit code from the check (0=success, 1=errors, 2=warnings with strict)'
  total-commits:
    description: 'Total number of commits checked'
  passing-commits:
    description: 'Number of commits that passed'
  error-count:
    description: 'Number of errors found'
  warning-count:
    description: 'Number of warnings found'

runs:
  using: 'composite'
  steps:
    - name: Cache omni-dev binary
      id: cache-omni-dev
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/omni-dev
        key: ${{ inputs.cache-prefix }}omni-dev-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}-${{ inputs.use-prebuilt-binary == 'true' && 'binary' || 'cargo' }}

    - name: Determine platform and download URL
      id: platform
      if: steps.cache-omni-dev.outputs.cache-hit != 'true' && inputs.use-prebuilt-binary == 'true'
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"

        # Determine the release tag
        if [ "$VERSION" = "latest" ]; then
          RELEASE_TAG=$(curl -s https://api.github.com/repos/rust-works/omni-dev/releases/latest | jq -r '.tag_name')
          if [ -z "$RELEASE_TAG" ] || [ "$RELEASE_TAG" = "null" ]; then
            echo "binary-available=false" >> $GITHUB_OUTPUT
            echo "::warning::Could not determine latest release tag"
            exit 0
          fi
        else
          RELEASE_TAG="v$VERSION"
        fi
        echo "release-tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

        # Determine platform-specific binary name
        OS="${{ runner.os }}"
        ARCH="${{ runner.arch }}"

        case "$OS" in
          Linux)
            BINARY_NAME="omni-dev-linux.tar.gz"
            ;;
          macOS)
            if [ "$ARCH" = "ARM64" ]; then
              BINARY_NAME="omni-dev-macos-arm64.tar.gz"
            else
              # x64 macOS binary not available yet
              echo "binary-available=false" >> $GITHUB_OUTPUT
              echo "available-platforms=Linux, macOS-ARM64, Windows" >> $GITHUB_OUTPUT
              echo "::warning::Pre-built binary not available for macOS x64. Available platforms: Linux, macOS-ARM64, Windows. Set 'use-prebuilt-binary: false' to build from source."
              exit 0
            fi
            ;;
          Windows)
            BINARY_NAME="omni-dev-windows.zip"
            ;;
          *)
            echo "binary-available=false" >> $GITHUB_OUTPUT
            echo "available-platforms=Linux, macOS-ARM64, Windows" >> $GITHUB_OUTPUT
            echo "::warning::Pre-built binary not available for $OS. Available platforms: Linux, macOS-ARM64, Windows. Set 'use-prebuilt-binary: false' to build from source."
            exit 0
            ;;
        esac

        DOWNLOAD_URL="https://github.com/rust-works/omni-dev/releases/download/${RELEASE_TAG}/${BINARY_NAME}"

        # Verify the binary exists
        HTTP_STATUS=$(curl -sL -o /dev/null -w "%{http_code}" "$DOWNLOAD_URL")
        if [ "$HTTP_STATUS" != "200" ] && [ "$HTTP_STATUS" != "302" ]; then
          echo "binary-available=false" >> $GITHUB_OUTPUT
          echo "available-platforms=Linux, macOS-ARM64, Windows" >> $GITHUB_OUTPUT
          echo "::warning::Pre-built binary not found at $DOWNLOAD_URL (HTTP $HTTP_STATUS). The version '$VERSION' may not have pre-built binaries. Set 'use-prebuilt-binary: false' to build from source, or use a version with available binaries."
          exit 0
        fi

        echo "binary-available=true" >> $GITHUB_OUTPUT
        echo "download-url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT
        echo "binary-name=$BINARY_NAME" >> $GITHUB_OUTPUT

    - name: Download pre-built binary
      if: steps.cache-omni-dev.outputs.cache-hit != 'true' && inputs.use-prebuilt-binary == 'true' && steps.platform.outputs.binary-available == 'true'
      shell: bash
      run: |
        mkdir -p ~/.cargo/bin
        DOWNLOAD_URL="${{ steps.platform.outputs.download-url }}"
        BINARY_NAME="${{ steps.platform.outputs.binary-name }}"

        echo "Downloading omni-dev from $DOWNLOAD_URL"
        curl -sL "$DOWNLOAD_URL" -o "/tmp/$BINARY_NAME"

        # Extract based on file type
        if [[ "$BINARY_NAME" == *.zip ]]; then
          unzip -q "/tmp/$BINARY_NAME" -d /tmp/omni-dev-extract
          # Find the binary (could be omni-dev.exe on Windows)
          find /tmp/omni-dev-extract -name "omni-dev*" -type f | head -1 | xargs -I {} mv {} ~/.cargo/bin/omni-dev
        else
          tar -xzf "/tmp/$BINARY_NAME" -C /tmp
          mv /tmp/omni-dev ~/.cargo/bin/omni-dev
        fi

        chmod +x ~/.cargo/bin/omni-dev
        echo "Successfully installed omni-dev from pre-built binary"
        ~/.cargo/bin/omni-dev --version

    - name: Fail if binary not available
      if: steps.cache-omni-dev.outputs.cache-hit != 'true' && inputs.use-prebuilt-binary == 'true' && steps.platform.outputs.binary-available == 'false'
      shell: bash
      run: |
        echo "::error::Pre-built binary not available for this platform/version. Set 'use-prebuilt-binary: false' to build from source."
        exit 1

    - name: Setup Rust toolchain
      if: steps.cache-omni-dev.outputs.cache-hit != 'true' && inputs.use-prebuilt-binary != 'true'
      uses: dtolnay/rust-toolchain@stable

    - name: Install omni-dev from source
      if: steps.cache-omni-dev.outputs.cache-hit != 'true' && inputs.use-prebuilt-binary != 'true'
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        echo "Installing omni-dev via cargo install..."
        if [ "$VERSION" = "latest" ]; then
          cargo install omni-dev
        else
          cargo install omni-dev --version "$VERSION"
        fi

    - name: Run commit check
      id: check
      shell: bash
      env:
        # API Keys
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}

        # Provider flags
        USE_OPENAI: ${{ inputs.use-openai }}
        USE_OLLAMA: ${{ inputs.use-ollama }}

        # Model configuration - only set if provided to avoid empty string issues
        ANTHROPIC_MODEL: ${{ inputs.model || '' }}
        OPENAI_MODEL: ${{ inputs.model || '' }}
        OLLAMA_MODEL: ${{ inputs.ollama-model || '' }}
        OLLAMA_BASE_URL: ${{ inputs.ollama-base-url || '' }}

        # Bedrock configuration
        CLAUDE_CODE_USE_BEDROCK: ${{ inputs.use-bedrock }}
        ANTHROPIC_BEDROCK_BASE_URL: ${{ inputs.bedrock-base-url || '' }}
        ANTHROPIC_AUTH_TOKEN: ${{ inputs.bedrock-auth-token || '' }}
        CLAUDE_CODE_SKIP_BEDROCK_AUTH: ${{ inputs.skip-bedrock-auth }}

        # Debug configuration
        RUST_LOG: ${{ inputs.debug == 'true' && 'debug' || '' }}
      run: |
        # Detect if we're on main/master branch (not in a PR)
        IS_MAIN_BRANCH="false"
        if [ -z "$GITHUB_BASE_REF" ]; then
          # Not a PR - check if we're on main or master
          if [ "$GITHUB_REF" = "refs/heads/main" ] || [ "$GITHUB_REF" = "refs/heads/master" ]; then
            IS_MAIN_BRANCH="true"
          fi
        fi

        if [ "$IS_MAIN_BRANCH" = "true" ] && [ "${{ inputs.skip-on-main }}" = "true" ]; then
          echo "Running on main branch - skipping commit check (cache populated)"
          echo "exit-code=0" >> $GITHUB_OUTPUT
          echo "result=Skipped on main branch" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Unset empty optional variables to let omni-dev use defaults
        [ -z "$OLLAMA_MODEL" ] && unset OLLAMA_MODEL
        [ -z "$OLLAMA_BASE_URL" ] && unset OLLAMA_BASE_URL
        [ -z "$ANTHROPIC_BEDROCK_BASE_URL" ] && unset ANTHROPIC_BEDROCK_BASE_URL
        [ -z "$ANTHROPIC_AUTH_TOKEN" ] && unset ANTHROPIC_AUTH_TOKEN
        [ -z "$RUST_LOG" ] && unset RUST_LOG

        # Build command arguments
        ARGS=()

        # Add optional flags
        if [ "${{ inputs.strict }}" = "true" ]; then
          ARGS+=("--strict")
        fi

        if [ "${{ inputs.quiet }}" = "true" ]; then
          ARGS+=("--quiet")
        fi

        if [ "${{ inputs.verbose }}" = "true" ]; then
          ARGS+=("--verbose")
        fi

        if [ "${{ inputs.show-passing }}" = "true" ]; then
          ARGS+=("--show-passing")
        fi

        if [ "${{ inputs.no-suggestions }}" = "true" ]; then
          ARGS+=("--no-suggestions")
        fi

        # Add optional parameters
        if [ -n "${{ inputs.model }}" ]; then
          ARGS+=("--model" "${{ inputs.model }}")
        fi

        if [ -n "${{ inputs.guidelines }}" ]; then
          ARGS+=("--guidelines" "${{ inputs.guidelines }}")
        fi

        if [ -n "${{ inputs.context-dir }}" ]; then
          ARGS+=("--context-dir" "${{ inputs.context-dir }}")
        fi

        if [ -n "${{ inputs.format }}" ]; then
          ARGS+=("--format" "${{ inputs.format }}")
        fi

        if [ -n "${{ inputs.batch-size }}" ]; then
          ARGS+=("--batch-size" "${{ inputs.batch-size }}")
        fi

        # Add commit range if specified
        if [ -n "${{ inputs.commit-range }}" ]; then
          ARGS+=("${{ inputs.commit-range }}")
        elif [ -n "${{ inputs.base-branch }}" ]; then
          # Calculate range from base branch
          ARGS+=("${{ inputs.base-branch }}..HEAD")
        elif [ -n "$GITHUB_BASE_REF" ]; then
          # In a PR context, use the PR base branch
          ARGS+=("origin/$GITHUB_BASE_REF..HEAD")
        fi

        # Run the check command and capture output
        set +e
        OUTPUT=$(omni-dev git commit message check "${ARGS[@]}" 2>&1)
        EXIT_CODE=$?
        set -e

        # Output to console
        echo "$OUTPUT"

        # Set outputs using environment files
        echo "exit-code=$EXIT_CODE" >> $GITHUB_OUTPUT

        # For multiline output, use heredoc syntax
        {
          echo "result<<EOF"
          echo "$OUTPUT"
          echo "EOF"
        } >> $GITHUB_OUTPUT

        # Parse summary if JSON format
        if [ "${{ inputs.format }}" = "json" ]; then
          TOTAL=$(echo "$OUTPUT" | jq -r '.summary.total_commits // 0' 2>/dev/null || echo "0")
          PASSING=$(echo "$OUTPUT" | jq -r '.summary.passing_commits // 0' 2>/dev/null || echo "0")
          ERRORS=$(echo "$OUTPUT" | jq -r '.summary.total_errors // 0' 2>/dev/null || echo "0")
          WARNINGS=$(echo "$OUTPUT" | jq -r '.summary.total_warnings // 0' 2>/dev/null || echo "0")

          echo "total-commits=$TOTAL" >> $GITHUB_OUTPUT
          echo "passing-commits=$PASSING" >> $GITHUB_OUTPUT
          echo "error-count=$ERRORS" >> $GITHUB_OUTPUT
          echo "warning-count=$WARNINGS" >> $GITHUB_OUTPUT
        fi

        # Exit with the original exit code
        exit $EXIT_CODE
